/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description [longitude, latitude] or [longitude, latitude, altitude]. */
        Position: number[];
        /** @description Bounding box [west, south, east, north] (or 3D variant). */
        BBox: number[];
        Point: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Point";
            coordinates: components["schemas"]["Position"];
        };
        MultiPoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPoint";
            coordinates: components["schemas"]["Position"][];
        };
        LineString: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LineString";
            coordinates: components["schemas"]["Position"][];
        };
        MultiLineString: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiLineString";
            coordinates: components["schemas"]["Position"][][];
        };
        Polygon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Polygon";
            coordinates: components["schemas"]["Position"][][];
        };
        MultiPolygon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPolygon";
            coordinates: components["schemas"]["Position"][][][];
        };
        GeometryCollection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GeometryCollection";
            geometries: components["schemas"]["Geometry"][];
        };
        /** @description Any GeoJSON geometry object. */
        Geometry: components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"];
        Feature: {
            /** @constant */
            type: "Feature";
            id?: string | number;
            geometry: components["schemas"]["Geometry"] | null;
            properties: {
                [key: string]: unknown;
            } | null;
            bbox?: components["schemas"]["BBox"];
        };
        FeatureCollection: {
            /** @constant */
            type: "FeatureCollection";
            features: components["schemas"]["Feature"][];
            bbox?: components["schemas"]["BBox"];
        };
        /** @enum {string} */
        Visibility: "public" | "private" | "shared";
        /** @description Fields shared by every managed resource. */
        ResourceBase: {
            id: number;
            name: string;
            description?: string | null;
            source?: string | null;
            owner_id?: number | null;
            visibility?: components["schemas"]["Visibility"];
            /** Format: date-time */
            created_at?: string | null;
        };
        /** @description A downloadable 3D model / file asset (e.g. glTF). */
        Asset: components["schemas"]["ResourceBase"] & {
            url: string;
            /** @description e.g. "gltf", "glb", "pointcloud". */
            asset_type?: string | null;
            filename?: string | null;
        };
        /** @description A Cesium 3D Tiles tileset. */
        Tileset: components["schemas"]["ResourceBase"] & {
            tileset_url: string;
            files_base_url?: string | null;
            root_file?: string | null;
            file_count?: number | null;
        };
        /** @description A WMS map layer offered by a provider/server. */
        WmsLayer: {
            id?: number | null;
            /** @description WMS server base URL (also the grouping key). */
            url: string;
            /** @description WMS layer name. */
            layer: string;
            description?: string | null;
        };
        /** @description A live/polled GeoJSON data source (mobility, sensors, ...). */
        RealtimeDataset: {
            id: string;
            name: string;
            description?: string | null;
            /** @description URL returning a GeoJSON FeatureCollection. */
            endpoint: string;
            /** @description Open vocabulary identifying the provider/feed, used for styling (e.g. "stib", "sncb", "bolt", "dott", "telraam", "sensor_community", "opensky"). */
            source_kind: string;
            /** @description Suggested polling interval; null for static. */
            poll_seconds?: number | null;
        };
        /** @enum {string} */
        PlaceKind: "region" | "municipality" | "district" | "monitoring_district" | "statistical_sector" | "site" | "custom";
        /** @description A georeferenced unit that indicators and scenarios attach to. Generic on purpose: a Brussels monitoring district, a TreeCity pilot site, or a single tree are all Places of different kinds. */
        Place: {
            id: string;
            name: string;
            kind: components["schemas"]["PlaceKind"];
            /** @description External code (NIS/LAU/INS, internal id, ...). */
            code?: string | null;
            /** @description Containing place, for hierarchies (region > district). */
            parent_id?: string | null;
            geometry?: components["schemas"]["Geometry"] | null;
            bbox?: components["schemas"]["BBox"];
            centroid?: components["schemas"]["Point"] | null;
            properties?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        IndicatorCategory: "population" | "environment" | "socioeconomic" | "heat_vulnerability" | "mobility" | "custom";
        /** @description Definition (metadata) of a measurable variable. */
        Indicator: {
            /** @description Stable machine key (e.g. "unemployment_rate"). */
            key: string;
            label: string;
            unit?: string | null;
            category: components["schemas"]["IndicatorCategory"];
            /**
             * @description Whether larger values are desirable (income) or not (unemployment). Drives color-scale direction and scenario delta coloring.
             * @default true
             */
            higher_is_better: boolean;
            description?: string | null;
        };
        TimeseriesPoint: {
            /** @description Year ("2024") or ISO-8601 date/datetime. */
            period: string;
            value?: number | null;
        };
        /** @description One indicator's values over time for one place. */
        Timeseries: {
            place_id: string;
            indicator_key: string;
            points: components["schemas"]["TimeseriesPoint"][];
        };
        /** @description A single observation (e.g. for a choropleth at one period). */
        IndicatorValue: {
            place_id: string;
            indicator_key: string;
            period: string;
            value?: number | null;
        };
        /**
         * @description Statistical model used to predict scenario outcomes.
         * @enum {string}
         */
        ModelKind: "linear" | "polynomial2" | "cart" | "knn";
        /** @description A user-set value overriding a predictor for what-if analysis. */
        ScenarioOverride: {
            place_id: string;
            indicator_key: string;
            value: number;
        };
        Scenario: {
            id: string;
            name: string;
            base_period?: string | null;
            model?: components["schemas"]["ModelKind"];
            overrides: components["schemas"]["ScenarioOverride"][];
            notes?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        };
        /** @enum {string} */
        JobStatus: "pending" | "running" | "succeeded" | "failed" | "cancelled";
        JobFile: {
            filename: string;
            url: string;
            /** @description e.g. "pointcloud", "report". */
            kind?: string | null;
            size_bytes?: number | null;
        };
        JobResult: {
            report?: {
                [key: string]: unknown;
            } | null;
            files?: components["schemas"]["JobFile"][];
        };
        /** @description A unit of long-running, step-based processing. */
        Job: {
            id: string;
            /** @description Pipeline identifier (e.g. "gpr", "ingest"). */
            kind: string;
            status: components["schemas"]["JobStatus"];
            progress_pct: number;
            current_step?: string | null;
            step_index?: number | null;
            step_count?: number | null;
            params?: {
                [key: string]: unknown;
            };
            result?: components["schemas"]["JobResult"] | null;
            error?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        PageMeta: {
            total: number;
            limit?: number | null;
            offset?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
