export { default as FButton } from './components/FButton.vue'
export { default as FCard } from './components/FCard.vue'
export { default as FCheckbox } from './components/FCheckbox.vue'
export { default as FChip } from './components/FChip.vue'
export { default as FSegmented } from './components/FSegmented.vue'
export { default as FSwitch } from './components/FSwitch.vue'
export { default as FSlider } from './components/FSlider.vue'
export { default as FYearSlider } from './components/FYearSlider.vue'
export { default as FChoroplethLegend } from './components/FChoroplethLegend.vue'
export type { ColorStop } from './components/FChoroplethLegend.vue'
