// Generates src/schemas.ts: flat, named type aliases for every schema in the
// OpenAPI document, so consumers can `import type { Place } from '@fari-brussels/twin-types'`
// instead of reaching into `components['schemas']['Place']`.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'

const here = dirname(fileURLToPath(import.meta.url))
const specPath = resolve(here, '../../../specs/openapi.yaml')
const outPath = resolve(here, '../src/schemas.ts')

const spec = parse(readFileSync(specPath, 'utf8'))
const names = Object.keys(spec?.components?.schemas ?? {})
if (names.length === 0) throw new Error(`No schemas found in ${specPath}`)

const lines = [
  '// AUTO-GENERATED by scripts/gen-aliases.mjs — do not edit by hand.',
  "import type { components } from './generated'",
  '',
  ...names.map((n) => `export type ${n} = components['schemas']['${n}']`),
  '',
]
writeFileSync(outPath, lines.join('\n'))
console.log(`wrote ${names.length} aliases -> ${outPath}`)
