# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Position(RootModel[list[float]]):
    """
    [longitude, latitude] or [longitude, latitude, altitude].
    """

    root: list[float] = Field(
        ...,
        description='[longitude, latitude] or [longitude, latitude, altitude].',
        max_length=3,
        min_length=2,
    )


class BBox(RootModel[list[float]]):
    """
    Bounding box [west, south, east, north] (or 3D variant).
    """

    root: list[float] = Field(
        ...,
        description='Bounding box [west, south, east, north] (or 3D variant).',
        max_length=6,
        min_length=4,
    )


class Point(BaseModel):
    type: Literal['Point']
    coordinates: Position


class MultiPoint(BaseModel):
    type: Literal['MultiPoint']
    coordinates: list[Position]


class LineString(BaseModel):
    type: Literal['LineString']
    coordinates: list[Position]


class MultiLineString(BaseModel):
    type: Literal['MultiLineString']
    coordinates: list[list[Position]]


class Polygon(BaseModel):
    type: Literal['Polygon']
    coordinates: list[list[Position]]


class MultiPolygon(BaseModel):
    type: Literal['MultiPolygon']
    coordinates: list[list[list[Position]]]


class Visibility(StrEnum):
    public = 'public'
    private = 'private'
    shared = 'shared'


class ResourceBase(BaseModel):
    """
    Fields shared by every managed resource.
    """

    id: int
    name: str
    description: str | None = None
    source: str | None = None
    owner_id: int | None = None
    visibility: Visibility | None = None
    created_at: AwareDatetime | None = None


class Asset(ResourceBase):
    """
    A downloadable 3D model / file asset (e.g. glTF).
    """

    url: str
    asset_type: str | None = Field(
        None, description='e.g. "gltf", "glb", "pointcloud".'
    )
    filename: str | None = None


class Tileset(ResourceBase):
    """
    A Cesium 3D Tiles tileset.
    """

    tileset_url: str
    files_base_url: str | None = None
    root_file: str | None = None
    file_count: int | None = None


class WmsLayer(BaseModel):
    """
    A WMS map layer offered by a provider/server.
    """

    id: int | None = None
    url: str = Field(..., description='WMS server base URL (also the grouping key).')
    layer: str = Field(..., description='WMS layer name.')
    description: str | None = None


class RealtimeDataset(BaseModel):
    """
    A live/polled GeoJSON data source (mobility, sensors, ...).
    """

    id: str
    name: str
    description: str | None = None
    endpoint: str = Field(..., description='URL returning a GeoJSON FeatureCollection.')
    source_kind: str = Field(
        ...,
        description='Open vocabulary identifying the provider/feed, used for styling (e.g. "stib", "sncb", "bolt", "dott", "telraam", "sensor_community", "opensky").\n',
    )
    poll_seconds: int | None = Field(
        None, description='Suggested polling interval; null for static.'
    )


class PlaceKind(StrEnum):
    region = 'region'
    municipality = 'municipality'
    district = 'district'
    monitoring_district = 'monitoring_district'
    statistical_sector = 'statistical_sector'
    site = 'site'
    custom = 'custom'


class IndicatorCategory(StrEnum):
    population = 'population'
    environment = 'environment'
    socioeconomic = 'socioeconomic'
    heat_vulnerability = 'heat_vulnerability'
    mobility = 'mobility'
    custom = 'custom'


class Indicator(BaseModel):
    """
    Definition (metadata) of a measurable variable.
    """

    key: str = Field(..., description='Stable machine key (e.g. "unemployment_rate").')
    label: str
    unit: str | None = None
    category: IndicatorCategory
    higher_is_better: bool | None = Field(
        True,
        description='Whether larger values are desirable (income) or not (unemployment). Drives color-scale direction and scenario delta coloring.\n',
    )
    description: str | None = None


class TimeseriesPoint(BaseModel):
    period: str = Field(..., description='Year ("2024") or ISO-8601 date/datetime.')
    value: float | None = None


class Timeseries(BaseModel):
    """
    One indicator's values over time for one place.
    """

    place_id: str
    indicator_key: str
    points: list[TimeseriesPoint]


class IndicatorValue(BaseModel):
    """
    A single observation (e.g. for a choropleth at one period).
    """

    place_id: str
    indicator_key: str
    period: str
    value: float | None = None


class ModelKind(StrEnum):
    """
    Statistical model used to predict scenario outcomes.
    """

    linear = 'linear'
    polynomial2 = 'polynomial2'
    cart = 'cart'
    knn = 'knn'


class ScenarioOverride(BaseModel):
    """
    A user-set value overriding a predictor for what-if analysis.
    """

    place_id: str
    indicator_key: str
    value: float


class Scenario(BaseModel):
    id: str
    name: str
    base_period: str | None = None
    model: ModelKind | None = None
    overrides: list[ScenarioOverride]
    notes: str | None = None
    created_at: AwareDatetime | None = None


class JobStatus(StrEnum):
    pending = 'pending'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    cancelled = 'cancelled'


class JobFile(BaseModel):
    filename: str
    url: str
    kind: str | None = Field(None, description='e.g. "pointcloud", "report".')
    size_bytes: int | None = None


class JobResult(BaseModel):
    report: dict[str, Any] | None = None
    files: list[JobFile] | None = None


class Job(BaseModel):
    """
    A unit of long-running, step-based processing.
    """

    id: str
    kind: str = Field(..., description='Pipeline identifier (e.g. "gpr", "ingest").')
    status: JobStatus
    progress_pct: float = Field(..., ge=0.0, le=100.0)
    current_step: str | None = None
    step_index: int | None = None
    step_count: int | None = None
    params: dict[str, Any] | None = None
    result: JobResult | None = None
    error: str | None = None
    created_at: AwareDatetime | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None


class PageMeta(BaseModel):
    total: int
    limit: int | None = None
    offset: int | None = None


class GeometryCollection(BaseModel):
    type: Literal['GeometryCollection']
    geometries: list[Geometry]


class Feature(BaseModel):
    type: Literal['Feature']
    id: str | int | None = None
    geometry: Geometry | None
    properties: dict[str, Any] | None
    bbox: BBox | None = None


class FeatureCollection(BaseModel):
    type: Literal['FeatureCollection']
    features: list[Feature]
    bbox: BBox | None = None


class Place(BaseModel):
    """
    A georeferenced unit that indicators and scenarios attach to. Generic on purpose: a Brussels monitoring district, a TreeCity pilot site, or a single tree are all Places of different kinds.

    """

    id: str
    name: str
    kind: PlaceKind
    code: str | None = Field(
        None, description='External code (NIS/LAU/INS, internal id, ...).'
    )
    parent_id: str | None = Field(
        None, description='Containing place, for hierarchies (region > district).'
    )
    geometry: Geometry | None = None
    bbox: BBox | None = None
    centroid: Point | None = None
    properties: dict[str, Any] | None = None


class Geometry(
    RootModel[
        Point
        | MultiPoint
        | LineString
        | MultiLineString
        | Polygon
        | MultiPolygon
        | GeometryCollection
    ]
):
    root: (
        Point
        | MultiPoint
        | LineString
        | MultiLineString
        | Polygon
        | MultiPolygon
        | GeometryCollection
    ) = Field(..., description='Any GeoJSON geometry object.', discriminator='type')


GeometryCollection.model_rebuild()
Feature.model_rebuild()
Place.model_rebuild()
