// Generates Vue icon components from the canonical FARI SVGs in ./svg.
// UI icons (all categories except demo) have their fills swapped to
// `currentColor` so they inherit text color; demo illustrations keep their
// original colors. Output is committed; re-run when the SVGs change.
import { promises as fs } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const svgDir = join(root, 'svg')
const genDir = join(root, 'src', 'generated')

const CATEGORIES = ['navigation', 'interface', 'content', 'user-system', 'feedback', 'demo']

const pascal = (s) =>
  s
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')

const slugify = (s) =>
  s
    .split(/[_\s-]+/)
    .filter(Boolean)
    .join('-')
    .toLowerCase()

function parseName(file) {
  let n = basename(file, '.svg')
    .replace(/^FARI_Icon_/, '')
    .replace(/^FARI_/, '')
  let variant = 'default'
  if (/_Black$/.test(n)) {
    variant = 'black'
    n = n.replace(/_Black$/, '')
  }
  return { base: n, variant }
}

const extractViewBox = (svg) => {
  const m = svg.match(/viewBox="([^"]+)"/)
  if (m) return m[1]
  const w = svg.match(/width="([0-9.]+)"/)
  const h = svg.match(/height="([0-9.]+)"/)
  return `0 0 ${w?.[1] ?? 24} ${h?.[1] ?? 24}`
}

const extractInner = (svg) => {
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/i)
  return (m ? m[1] : '').trim()
}

// Swap non-white fills/strokes to currentColor so the icon themes with text color.
const themeify = (inner) =>
  inner.replace(/(fill|stroke)="(#[0-9a-fA-F]{3,8}|black)"/g, (full, attr, val) => {
    const v = val.toLowerCase()
    if (v === '#fff' || v === '#ffffff' || v === 'white') return full
    return `${attr}="currentColor"`
  })

async function main() {
  const icons = []
  for (const cat of CATEGORIES) {
    let files
    try {
      files = await fs.readdir(join(svgDir, cat))
    } catch {
      continue
    }
    for (const file of files.filter((f) => f.endsWith('.svg')).sort()) {
      const svg = await fs.readFile(join(svgDir, cat, file), 'utf8')
      const { base, variant } = parseName(file)
      // Every FARI icon is monochrome (#575757) with optional white knockouts;
      // themeify swaps the dark fills to currentColor (white preserved) so the
      // whole set inherits text color.
      const inner = themeify(extractInner(svg))
      icons.push({
        comp: 'Icon' + pascal(base) + (variant === 'black' ? 'Black' : ''),
        slug: slugify(base) + (variant === 'black' ? '-black' : ''),
        viewBox: extractViewBox(svg),
        inner,
        category: cat,
      })
    }
  }
  icons.sort((a, b) => a.comp.localeCompare(b.comp))

  const iconsTs =
    [
      '// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.',
      "import { makeIcon } from '../make-icon'",
      '',
      ...icons.map(
        (i) =>
          `export const ${i.comp} = /*#__PURE__*/ makeIcon(${JSON.stringify(i.comp)}, ${JSON.stringify(i.viewBox)}, ${JSON.stringify(i.inner)})`,
      ),
    ].join('\n') + '\n'

  const registryTs =
    [
      '// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.',
      "import type { Component } from 'vue'",
      'import {',
      ...icons.map((i) => `  ${i.comp},`),
      "} from './icons'",
      '',
      'export type IconName =',
      ...icons.map((i) => `  | ${JSON.stringify(i.slug)}`),
      '',
      'export const icons: Record<IconName, Component> = {',
      ...icons.map((i) => `  ${JSON.stringify(i.slug)}: ${i.comp},`),
      '}',
      '',
      'export const iconNames = Object.keys(icons) as IconName[]',
    ].join('\n') + '\n'

  await fs.mkdir(genDir, { recursive: true })
  await fs.writeFile(join(genDir, 'icons.ts'), iconsTs)
  await fs.writeFile(join(genDir, 'registry.ts'), registryTs)
  console.log(`generated ${icons.length} icons -> ${genDir}`)
}

main()
